
trigger:
  branches:
    exclude:
      - 'dharanesh_main_branch'
    include:
      - 'master'



jobs:
- job: RunTests
  timeoutInMinutes: 0
  pool:
    name: SeleniumAgentsPool
    demands:
    - maven
    - Agent.Name -equals CW721AdoAgent
  steps:
    - task: Maven@3
      displayName: 'Smoke TestNG'
      inputs:
       mavenPomFile: 'pom.xml'
       mavenOptions: '-Xmx10240m'
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.8'
       jdkDirectory: 'C:\Program Files\Java\jdk1.8.0_281\bin'
       jdkArchitectureOption: 'x64'
       publishJUnitResults: true
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       goals: 'clean install'
      #testRunTitle: # Optional
      #allowBrokenSymlink: false # Optional. Has effect only when publishJUnitResults == True
      #codeCoverageToolOption: 'None' # Optional. Options: none, cobertura, jaCoCo. Enabling code coverage inserts the `clean` goal into the Maven goals list when Maven runs.
      #codeCoverageClassFilter: # Optional. Comma-separated list of filters to include or exclude classes from collecting code coverage. For example: +:com.*,+:org.*,-:my.app*.*
      #codeCoverageClassFilesDirectories: # Optional
      #codeCoverageSourceDirectories: # Optional
      #codeCoverageFailIfEmpty: false # Optional
      #jdkVersionOption: 'default' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
      #jdkArchitectureOption: 'x64' # Optional. Options: x86, x64
      #mavenVersionOption: 'Default' # Options: default, path
      #mavenDirectory: # Required when mavenVersionOption == Path
      #mavenSetM2Home: false # Required when mavenVersionOption == Path
      #mavenOptions: '-Xmx1024m' # Optional
      #mavenAuthenticateFeed: false
      #effectivePomSkip: false
      #sonarQubeRunAnalysis: false
      #sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom
      #checkStyleRunAnalysis: false # Optional
      #pmdRunAnalysis: false # Optional
      #findBugsRunAnalysis: false # Optional
